import { FoodType } from '../models/enums';
import { MenuItem } from '../models/menu-item.model';

export const MENU_ITEMS: MenuItem[] = [
  // Meghana Foods – Koramangala
  { id: 1, restaurantId: 1, name: 'Boneless Chicken Biryani', description: 'Fragrant long grain rice with succulent chicken pieces.', price: 240, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/meghana/boneless chicken biryani.png', category: 'Biryani', isBestSeller: true, rating: 4.6 },
  { id: 2, restaurantId: 1, name: 'Veg Biryani', description: 'Seasonal vegetables cooked with basmati rice and spices.', price: 180, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/meghana/veg biryani.png', category: 'Biryani', isBestSeller: false, rating: 4.3 },
  { id: 3, restaurantId: 1, name: 'Pepper Chicken Dry', description: 'Pan tossed chicken with black pepper and curry leaves.', price: 170, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/meghana/pepper chicken dry.png', category: 'Starters', isBestSeller: true, rating: 4.5 },
  { id: 4, restaurantId: 1, name: 'Gobi Manchurian', description: 'Crispy cauliflower tossed in Indo-Chinese sauce.', price: 130, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/meghana/gobi manchurian.png', category: 'Starters', isBestSeller: false },
  { id: 5, restaurantId: 1, name: 'Chicken 65', description: 'Andhra style deep-fried chicken with curry leaves.', price: 175, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/meghana/chicken 65.png', category: 'Starters', isBestSeller: true },
  { id: 6, restaurantId: 1, name: 'Paneer Butter Masala', description: 'Rich tomato gravy with soft paneer cubes.', price: 190, foodType: FoodType.Veg, spiceLevel: 'Mild', imageUrl: 'assets/images/foods/meghana/paneer-butter-masala-1.png', category: 'Main Course', isBestSeller: false },
  { id: 7, restaurantId: 1, name: 'Hyderabadi Chicken Curry', description: 'Home-style chicken curry with Andhra spices.', price: 210, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/meghana/hyderabadi chicken curry.png', category: 'Main Course', isBestSeller: false },
  { id: 8, restaurantId: 1, name: 'Egg Biryani', description: 'Fluffy rice layered with masala eggs.', price: 190, foodType: FoodType.Egg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/meghana/egg biryani.jpg', category: 'Biryani', isBestSeller: false },
  { id: 9, restaurantId: 1, name: 'Curd Rice', description: 'Comforting curd rice tempered with mustard and curry leaves.', price: 90, foodType: FoodType.Veg, spiceLevel: 'Mild', imageUrl: 'assets/images/foods/meghana/curd_rice.jpg', category: 'South Indian', isBestSeller: false },
  { id: 10, restaurantId: 1, name: 'Gulab Jamun', description: 'Warm khoya dumplings soaked in sugar syrup.', price: 90, foodType: FoodType.Veg, imageUrl: 'assets/images/foods/meghana/gulab jamun.png', category: 'Desserts', isBestSeller: false },

  // Nagarjuna – Residency Road
  { id: 11, restaurantId: 2, name: 'Andhra Meals', description: 'Complete Andhra meal with curries, dal, curd and dessert.', price: 220, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/nagarjuna/andhra meals.jpg', category: 'Meals', isBestSeller: true },
  { id: 12, restaurantId: 2, name: 'Chicken Biryani', description: 'Signature biryani cooked in Andhra spices.', price: 260, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/nagarjuna/chicken biryani.png', category: 'Biryani', isBestSeller: true },
  { id: 13, restaurantId: 2, name: 'Mutton Fry', description: 'Slow cooked mutton tossed with pepper and onions.', price: 180, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/nagarjuna/mutton fry.png', category: 'Starters', isBestSeller: false },
  { id: 14, restaurantId: 2, name: 'Baby Corn 65', description: 'Crispy fried baby corn with curry leaves.', price: 150, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: 'https://picsum.photos/seed/nagarjuna-babycorn/800/500', category: 'Starters', isBestSeller: false },
  { id: 15, restaurantId: 2, name: 'Gongura Chicken', description: 'Tangy gongura based chicken curry.', price: 240, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: 'assets/images/foods/nagarjuna/gongura chicken.webp', category: 'Main Course', isBestSeller: false },
  { id: 16, restaurantId: 2, name: 'Veg Pulao', description: 'Mild pulao with vegetables and whole spices.', price: 150, foodType: FoodType.Veg, spiceLevel: 'Mild', imageUrl: 'assets/images/foods/nagarjuna/veg pulao.png', category: 'Rice', isBestSeller: false },
  { id: 17, restaurantId: 2, name: 'Egg Roast', description: 'Pan roasted eggs with pepper masala.', price: 140, foodType: FoodType.Egg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/nagarjuna/egg roast.jpg', category: 'Starters', isBestSeller: false },
  { id: 18, restaurantId: 2, name: 'Chilli Paneer', description: 'Indo-Chinese paneer stir fry.', price: 150, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: 'assets/images/foods/nagarjuna/chilli paneer.jpg', category: 'Starters', isBestSeller: false },
  { id: 19, restaurantId: 2, name: 'Curd Rice', description: 'Tempered curd rice with pomegranate.', price: 120, foodType: FoodType.Veg, imageUrl: 'assets/images/foods/nagarjuna/curd rice.png', category: 'Meals', isBestSeller: false },
  { id: 20, restaurantId: 2, name: 'Double Ka Meetha', description: 'Bread pudding with saffron and nuts.', price: 110, foodType: FoodType.Veg, imageUrl: 'assets/images/foods/nagarjuna/double ka meetha.jpg', category: 'Desserts', isBestSeller: false },

  // Empire Restaurant – Church Street
  { id: 21, restaurantId: 3, name: 'Shawarma Roll', description: 'Juicy chicken wrapped in pita with garlic mayo.', price: 170, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/empire/shawarma.png', category: 'Grills', isBestSeller: true, rating: 4.4 },
  { id: 22, restaurantId: 3, name: 'Empire Special Biryani', description: 'Legendary biryani with aromatic spices.', price: 270, foodType: FoodType.NonVeg, spiceLevel: 'Medium', imageUrl: '/assets/images/foods/empire/special biryani.avif', category: 'Biryani', isBestSeller: true },
  { id: 23, restaurantId: 3, name: 'Pepper BBQ Chicken', description: 'Char-grilled chicken with pepper rub.', price: 220, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: '/assets/images/foods/empire/peppe bbq chicken.png', category: 'Grills', isBestSeller: false },
  { id: 24, restaurantId: 3, name: 'Chicken Kebab', description: 'Skewered kebabs roasted to perfection.', price: 210, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/empire/chicken kebab.jpg', category: 'Grills', isBestSeller: false },
  { id: 25, restaurantId: 3, name: 'Paneer Tikka', description: 'Char-grilled paneer with spices.', price: 180, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/empire/paneer tikka.avif', category: 'Grills', isBestSeller: false },
  { id: 26, restaurantId: 3, name: 'Chicken Ghee Roast', description: 'Mangalorean style spicy ghee roast.', price: 240, foodType: FoodType.NonVeg, spiceLevel: 'Spicy', imageUrl: '/assets/images/foods/empire/chicken-ghee-roast.jpg', category: 'Main Course', isBestSeller: false },
  { id: 27, restaurantId: 3, name: 'Kothu Parotta', description: 'Shredded parotta tossed with eggs and meat.', price: 190, foodType: FoodType.Egg, spiceLevel: 'Medium', imageUrl: '/assets/images/foods/empire/egg_kothu_parotta.avif', category: 'Main Course', isBestSeller: false },
  { id: 28, restaurantId: 3, name: 'Chicken Fried Rice', description: 'Wok tossed rice with chicken and veggies.', price: 160, foodType: FoodType.NonVeg, spiceLevel: 'Mild', imageUrl: '/assets/images/foods/empire/chicken fried rice.avif', category: 'Rice', isBestSeller: false },
  { id: 29, restaurantId: 3, name: 'Egg Curry', description: 'Boiled eggs simmered in spicy gravy.', price: 170, foodType: FoodType.Egg, spiceLevel: 'Medium', imageUrl: '/assets/images/foods/empire/egg curry.jpg', category: 'Main Course', isBestSeller: false },
  { id: 30, restaurantId: 3, name: 'Falooda', description: 'Rose syrup dessert with vermicelli and ice cream.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/empire/falooda.avif', category: 'Desserts', isBestSeller: false },

  // Truffles – Indiranagar
  { id: 31, restaurantId: 4, name: 'All American Cheese Burger', description: 'Juicy patty with double cheese and fresh lettuce.', price: 220, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/truffles/cheeseburger.jpg', category: 'Burgers', isBestSeller: true },
  { id: 32, restaurantId: 4, name: 'Peri Peri Chicken Steak', description: 'Grilled chicken steak with spicy peri peri sauce.', price: 260, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/truffles/chicken steak.jpg', category: 'Grills', isBestSeller: false },
  { id: 33, restaurantId: 4, name: 'Veggie Crunch Burger', description: 'Crispy veg patty with spicy mayo.', price: 180, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/truffles/veggie crunch burger.jpg', category: 'Burgers', isBestSeller: false },
  { id: 34, restaurantId: 4, name: 'Mushroom & Cheese Omelette', description: 'Three egg omelette with mushrooms and cheese.', price: 140, foodType: FoodType.Egg, imageUrl: '/assets/images/foods/truffles/mushroom-tarragon-cheddar-omelette-18.webp', category: 'Breakfast', isBestSeller: false },
  { id: 35, restaurantId: 4, name: 'BBQ Chicken Pizza', description: 'Thin crust pizza with BBQ chicken and onions.', price: 260, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/truffles/AR-24878-bbq-chicken-pizza-beauty-4x3-39cd80585ad04941914dca4bd82eae3d.jpg', category: 'Main Course', isBestSeller: true },
  { id: 36, restaurantId: 4, name: 'Four Cheese Pasta', description: 'Creamy pasta loaded with four cheeses.', price: 230, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/truffles/featured-image-four-cheese-pasta-cheesecake-factory-225x225.webp', category: 'Main Course', isBestSeller: false },
  { id: 37, restaurantId: 4, name: 'Chicken Wings', description: 'Crispy wings tossed in spicy sauce.', price: 170, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/truffles/Truffle-Parmesan-Chicken-Wings-Frydae-040519-05.jpg', category: 'Starters', isBestSeller: false },
  { id: 38, restaurantId: 4, name: 'Loaded Nachos', description: 'Corn chips loaded with beans, cheese and salsa.', price: 150, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/truffles/truffle_nacho_loaded_fries_taco_bell_copycat_019.jpg', category: 'Starters', isBestSeller: false },
  { id: 39, restaurantId: 4, name: 'Chocolate Truffle Cake Slice', description: 'Rich chocolate cake with ganache.', price: 130, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/truffles/Truffle_1_1800x1800 cake.webp', category: 'Desserts', isBestSeller: true },
  { id: 40, restaurantId: 4, name: 'Cold Coffee Frappe', description: 'Blended coffee with ice cream.', price: 140, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/truffles/coffee-ice-cream-frappe-frappuccino-3.jpg', category: 'Beverages', isBestSeller: false },

  // MTR – Lalbagh Road
  { id: 41, restaurantId: 5, name: 'Masala Dosa', description: 'Crispy dosa with spiced potato filling.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/masala dosa.jpg', category: 'South Indian', isBestSeller: true },
  { id: 42, restaurantId: 5, name: 'Rava Idli', description: 'Steamed semolina idli served with chutney.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/rava-idli.jpg', category: 'South Indian', isBestSeller: true },
  { id: 43, restaurantId: 5, name: 'Kesari Bath', description: 'Sweet semolina dessert with ghee and nuts.', price: 80, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/Kesari-Bhath-2-ovz6qme4qkwroca938x4ujpx8m3f1valafj4ca6sus.jpg', category: 'Desserts', isBestSeller: false },
  { id: 44, restaurantId: 5, name: 'Poori Sagu', description: 'Fluffy poori with vegetable sagu.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/poori sagu.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 45, restaurantId: 5, name: 'Filter Coffee', description: 'Traditional South Indian filter coffee.', price: 70, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/mtr-filter-coffee-stands.jpg', category: 'Beverages', isBestSeller: true },
  { id: 46, restaurantId: 5, name: 'Mini Meals', description: 'Set meals with rice, sambar, rasam and sweet.', price: 180, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/mini meals.jpg', category: 'Meals', isBestSeller: false },
  { id: 47, restaurantId: 5, name: 'Chow Chow Bath', description: 'Combination of khara bath and kesari bath.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/Chow-chow-Bhath-1024x595.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 48, restaurantId: 5, name: 'Bisi Bele Bath', description: 'Rice and lentils cooked with spices and veggies.', price: 160, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/bisibelebath-with-ghee.jpg', category: 'Main Course', isBestSeller: false },
  { id: 49, restaurantId: 5, name: 'Pineapple Kesari', description: 'Kesari bath with pineapple chunks.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/pineapple-kesari-final-500x375.jpg', category: 'Desserts', isBestSeller: false },
  { id: 50, restaurantId: 5, name: 'Vada Sambhar', description: 'Crispy vada served with hot sambhar.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/mtr/vada sambar.avif', category: 'Snacks', isBestSeller: false },

  // CTR Sri Sagar – Malleshwaram
  { id: 51, restaurantId: 6, name: 'Benne Masala Dosa', description: 'Butter rich dosa with potato filling.', price: 130, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/benne masala dosa.avif', category: 'South Indian', isBestSeller: true },
  { id: 52, restaurantId: 6, name: 'Plain Dosa', description: 'Crispy plain dosa served with chutney.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/plain dosa.avif', category: 'South Indian', isBestSeller: false },
  { id: 53, restaurantId: 6, name: 'Maddur Vada', description: 'Crispy vada with onions and curry leaves.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/maddur vada.jpg', category: 'Snacks', isBestSeller: false },
  { id: 54, restaurantId: 6, name: 'Khara Bath', description: 'Savory semolina upma with veggies.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/khara bath.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 55, restaurantId: 6, name: 'Filter Coffee', description: 'Frothy filter coffee served hot.', price: 70, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/filter coffee.jpg', category: 'Beverages', isBestSeller: true },
  { id: 56, restaurantId: 6, name: 'Idli Vada Combo', description: 'Soft idlis paired with crispy vada.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/idli vada.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 57, restaurantId: 6, name: 'Kesari Bath', description: 'Sweet saffron semolina dessert.', price: 80, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/kesari bath.jpg', category: 'Desserts', isBestSeller: false },
  { id: 58, restaurantId: 6, name: 'Set Dosa', description: 'Set of soft fluffy dosas.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/default-south-indian-restaurants-20.avif', category: 'South Indian', isBestSeller: false },
  { id: 59, restaurantId: 6, name: 'Mangalore Bajji', description: 'Spiced fritters served with chutney.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/mangalore-bajji.webp', category: 'Snacks', isBestSeller: false },
  { id: 60, restaurantId: 6, name: 'Lemon Rice', description: 'Tangy rice tempered with peanuts.', price: 130, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/ctr/lemon rice.jpg', category: 'Main Course', isBestSeller: false },

  // Brahmin’s Coffee Bar – Basavanagudi
  { id: 61, restaurantId: 7, name: 'Idli Vada', description: 'Soft idlis with crispy vada and chutney.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/idli vada.avif', category: 'Breakfast', isBestSeller: true },
  { id: 62, restaurantId: 7, name: 'Khara Bath', description: 'Savory upma with vegetables.', price: 85, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/khara bath.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 63, restaurantId: 7, name: 'Kesari Bath', description: 'Sweet semolina with saffron.', price: 80, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/kesari bath.jpg', category: 'Desserts', isBestSeller: false },
  { id: 64, restaurantId: 7, name: 'Bisibele Bath', description: 'Rice with lentils and vegetables.', price: 140, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/bisibele-bath.jpg', category: 'Main Course', isBestSeller: false },
  { id: 65, restaurantId: 7, name: 'Masala Dosa', description: 'Crisp dosa with potato filling.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/benne masala dosa.avif', category: 'South Indian', isBestSeller: false },
  { id: 66, restaurantId: 7, name: 'Filter Coffee', description: 'Hot, strong filter coffee.', price: 60, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/filter coffee.jpg', category: 'Beverages', isBestSeller: true },
  { id: 67, restaurantId: 7, name: 'Curd Rice', description: 'Refreshing curd rice.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/curd rice.png', category: 'Meals', isBestSeller: false },
  { id: 68, restaurantId: 7, name: 'Mangalore Bonda', description: 'Soft bondas with chutney.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/mangalore bonda.jpg', category: 'Snacks', isBestSeller: false },
  { id: 69, restaurantId: 7, name: 'Plain Dosa', description: 'Golden crisp plain dosa.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/plain dosa.avif', category: 'South Indian', isBestSeller: false },
  { id: 70, restaurantId: 7, name: 'Avalakki', description: 'Seasoned flattened rice with peanuts.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/brahmins/avalakki.jpg', category: 'Breakfast', isBestSeller: false },

  // Vidyarthi Bhavan – Gandhi Bazaar
  { id: 71, restaurantId: 8, name: 'Special Masala Dosa', description: 'Iconic thick dosa with potato masala.', price: 140, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/masala dosa.jpg', category: 'South Indian', isBestSeller: true },
  { id: 72, restaurantId: 8, name: 'Rava Vada', description: 'Crispy rava vada with coconut chutney.', price: 85, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/the-rava-vada.jpg', category: 'Snacks', isBestSeller: false },
  { id: 73, restaurantId: 8, name: 'Puri Sagu', description: 'Poori served with vegetable sagu.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/puri sagu.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 74, restaurantId: 8, name: 'Kesari Bath', description: 'Sweet semolina dessert.', price: 80, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/kesari bath.avif', category: 'Desserts', isBestSeller: false },
  { id: 75, restaurantId: 8, name: 'Khara Bath', description: 'Savory upma with veggies.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/khara-bath.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 76, restaurantId: 8, name: 'Filter Coffee', description: 'Strong filter coffee in steel tumbler.', price: 70, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/filter coffee.jpg', category: 'Beverages', isBestSeller: true },
  { id: 77, restaurantId: 8, name: 'Chow Chow Bath', description: 'Sweet and savory combo plate.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/chow chow bath.jpg', category: 'Breakfast', isBestSeller: false },
  { id: 78, restaurantId: 8, name: 'Uddina Vada', description: 'Crispy urad dal vada.', price: 80, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/uddina vada.jpg', category: 'Snacks', isBestSeller: false },
  { id: 79, restaurantId: 8, name: 'Curd Rice', description: 'Cooling curd rice tempered with mustard.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/curd-rice-thayir-sadam-480x270.jpg', category: 'Meals', isBestSeller: false },
  { id: 80, restaurantId: 8, name: 'Lemon Rice', description: 'Citrusy rice with peanuts and chilies.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/vidyarthi/lemon-rice-how-to-make-lemon-rice-31-scaled.jpg', category: 'Main Course', isBestSeller: false },

  // Anand Sweets & Savouries – Commercial Street
  { id: 81, restaurantId: 9, name: 'Kaju Katli', description: 'Classic cashew fudge with silver leaf.', price: 130, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/kaju katli.jpg', category: 'Desserts', isBestSeller: true },
  { id: 82, restaurantId: 9, name: 'Mysore Pak', description: 'Ghee-rich gram flour fudge.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/Mysore_pak_Celebration.jpg', category: 'Desserts', isBestSeller: true },
  { id: 83, restaurantId: 9, name: 'Badam Milk', description: 'Chilled almond milk with saffron.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/badam-milk-recipe.webp', category: 'Beverages', isBestSeller: false },
  { id: 84, restaurantId: 9, name: 'Chole Bhature', description: 'Puffy bhature with spicy chole.', price: 180, foodType: FoodType.Veg, spiceLevel: 'Medium', imageUrl: '/assets/images/foods/anand/bhatura-with-chole.jpg', category: 'North Indian', isBestSeller: false },
  { id: 85, restaurantId: 9, name: 'Pani Puri', description: 'Crisp puris with spiced water.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/pani puri.jpg', category: 'Street Food', isBestSeller: false },
  { id: 86, restaurantId: 9, name: 'Jalebi', description: 'Crispy jalebi soaked in sugar syrup.', price: 100, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/jalebi.avif', category: 'Desserts', isBestSeller: false },
  { id: 87, restaurantId: 9, name: 'Rasmalai', description: 'Soft paneer patties in sweet milk.', price: 130, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/Rasmalai-recipe@palates-desire.jpg', category: 'Desserts', isBestSeller: false },
  { id: 88, restaurantId: 9, name: 'Samosa', description: 'Crisp pastry filled with potatoes and peas.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/samosa-recipe-500x375.jpg', category: 'Snacks', isBestSeller: false },
  { id: 89, restaurantId: 9, name: 'Aloo Tikki Chaat', description: 'Potato patties topped with chutneys.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/aloo tikki chaat.jpg', category: 'Street Food', isBestSeller: false },
  { id: 90, restaurantId: 9, name: 'Dry Fruit Lassi', description: 'Creamy yogurt drink with nuts.', price: 120, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/anand/Best-Dry-Fruit-Lassi.jpg', category: 'Beverages', isBestSeller: false },

  // Leon Grill – HSR Layout
  { id: 91, restaurantId: 10, name: 'Peri Peri Chicken Bowl', description: 'Grilled chicken with peri peri sauce over rice.', price: 240, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/leon grill/peri peri chicken bowl.avif', category: 'Bowls', isBestSeller: true },
  { id: 92, restaurantId: 10, name: 'Classic Chicken Burger', description: 'Crispy chicken patty with fresh veggies.', price: 200, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/leon grill/chicken burger.avif', category: 'Burgers', isBestSeller: true },
  { id: 93, restaurantId: 10, name: 'Grilled Paneer Bowl', description: 'Charred paneer with herbed rice and veggies.', price: 220, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/paneer bowl.jpg', category: 'Bowls', isBestSeller: false },
  { id: 94, restaurantId: 10, name: 'Chicken Shawarma Wrap', description: 'Shawarma wrap with garlic dip.', price: 180, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/leon grill/shawarma.avif', category: 'Wraps', isBestSeller: false },
  { id: 95, restaurantId: 10, name: 'Falafel Wrap', description: 'Crispy falafel with hummus and salad.', price: 160, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/falafel wrap.avif', category: 'Wraps', isBestSeller: false },
  { id: 96, restaurantId: 10, name: 'Spicy Chicken Wings', description: 'Smoky wings with spicy rub.', price: 170, foodType: FoodType.NonVeg, imageUrl: '/assets/images/foods/leon grill/chicken wings.avif', category: 'Starters', isBestSeller: false },
  { id: 97, restaurantId: 10, name: 'Veg Loaded Fries', description: 'Fries topped with cheese and veggies.', price: 140, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/loaded fries.avif', category: 'Sides', isBestSeller: false },
  { id: 98, restaurantId: 10, name: 'Hummus with Pita', description: 'Creamy hummus served with warm pita bread.', price: 140, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/hummus pita.webp', category: 'Starters', isBestSeller: false },
  { id: 99, restaurantId: 10, name: 'Chocolate Brownie', description: 'Fudgy brownie with chocolate chips.', price: 110, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/brownie.jpg', category: 'Desserts', isBestSeller: false },
  { id: 100, restaurantId: 10, name: 'Iced Lemon Tea', description: 'Refreshing lemon iced tea.', price: 90, foodType: FoodType.Veg, imageUrl: '/assets/images/foods/leon grill/lemon tea.jpg', category: 'Beverages', isBestSeller: false }
];
